### ISSUE TITLE
Invalid characters 'L' and 'I' are not detected as illegal

### ISSUE THREAD

**Issue by gsantoro** [huxi/sulky#2]
If I try to decode the invalid ULID 'UUUUUUUUUUUUUUUUUUUUUUUUUU' it will complain with exception IllegalArgumentException("Illegal character: 'U'") while if you try to decode the invalid ULID 'IIIIIIIIIIIIIIIIIIIIIIIIII' or 'LLLLLLLLLLLLLLLLLLLLLLLLLL' you will get a valid ULID with bytes representation in hexadecimal '0021084210842108421084210842108421'

**Comment by huxi** [comment]
This is by design.

See the [Base32 Encoding](http://crockford.com/wrmg/base32.html) spec.

> When decoding, upper and lower case letters are accepted, and i and l will be treated as 1 and o will be treated as 0. When encoding, only upper case letters are used.

`'IIIIIIIIIIIIIIIIIIIIIIIIII'` and `'LLLLLLLLLLLLLLLLLLLLLLLLLL'` aren't really illegal. They both map to `'11111111111111111111111111'`.

The idea is that decoding should be forgiving errors in case of manual entry and mix-up of letters while encoding should always be strict and correct.

Good catch, though. :)

**Comment by gsantoro** [comment]
Thanks for the explanation.

**Comment by vastpn** [comment]
Thanks for the explanation！I ignored UNIX time。
