### ISSUE TITLE
Seek ulid technical help

### ISSUE THREAD

**Issue by vastpn** [huxi/sulky#5]
dear  huxi:
    Recently, we have been studying ulid project and intend to use it for Java distributed microservice project. Also known as https://medium.com/zendesk-engineering/how-probable-are-collisions-with-ulids-monotonic-option-d604d3ed2de But there are many problems in the core computing logic. Can you give us some guidance on the following questions, thank you!

    List of questions:
    1、“ulidString must not exceed '7ZZZZZZZZZZZZZZZZZZZZZZZZZ'”，Why not "YZZZZZZZZZZZZZZZZZZZZZZZZZ"?
    2、Is the maximum time stamp support like this:  (32^10 -1) / (365 * 86400000)   Or  (2^48 -1) / (365* 86400000)
    3、Why “TIMESTAMP_OVERFLOW_MASK”、“TIMESTAMP_MSB_MASK” is chosen as the critical value reference?
    4、What is the derivation formula of X, y value?
    5、"Won't run out of space till the year 10889 AD"，What is the derivation formula of 10889 value?
                                                                                                                                                                                Chinese friends，
                                                                                                                                                                                lin tan

**Comment by huxi** [comment]
This is just an implementation of the [ULID Spec](https://github.com/ulid/spec).

```
 01AN4Z07BY      79KA1307SR9X4MV3

|----------|    |----------------|
 Timestamp          Randomness
   48bits             80bits
```

A `ULID` is a 128bit datatype. 128bits of 1 expressed via [Crockford](https://www.crockford.com/base32.html) happens to be `7ZZZZZZZZZZZZZZZZZZZZZZZZZ`. Therefore bigger numbers encoded in Crockford won't fit into the 128bit of the data type. Trying to parse them is an error.

There are 48 bits reserved for timestamp which is defined to contain ms of [Unix time](https://en.wikipedia.org/wiki/Unix_time). Those 48 bits will overflow precisely 1ms after `+10889-08-02T05:31:50.655Z` - and since that would break lexicographical sorting (the whole point of ULID vs. just random bits) it is considered an error.

Hope that helps.

**Comment by vastpn** [comment]
Thank you very much for your explanation! In the process of analysis, I ignored the key points of high order sorting and binary overflow.
